title: Your Project Title
description: A brief description of your project.
author:
  name: Your Team Members
  mentor: Mentor Name
theme: minima # Or a theme of your choice that supports custom layouts

# Custom variables for your sections
sections:
  landing:
    title: Your Project Title
    members: Your Team Members
    mentor: Mentor Name
    github_link: "YOUR_GITHUB_REPO_LINK"
    drive_link: "YOUR_GOOGLE_DRIVE_LINK"
  introduction:
    title: Introduction
    content: |
      This section provides an introduction to your project. 
      [Add detailed information here.]
  methodology:
    title: Methodology
    content: |
      Here, you'll describe the methods used in your project.
      [Add detailed information here.]
  workflow:
    title: Workflow & Discussion
    content: |
      This section details the workflow and offers a discussion of the results.
      [Add detailed information here.]