title: Your Project Title
description: A brief description of your project.
author:
  name: Your Team Members
  mentor: Mentor Name
theme: minima # Or a theme of your choice that supports custom layouts
plugins:
  - jekyll-paginate
paginate: 5

# Custom variables for your sections
sections:
  landing:
    title: Your Project Title
    members: Your Team Members
    mentor: Mentor Name
    github_link: "YOUR_GITHUB_REPO_LINK"
    drive_link: "YOUR_GOOGLE_DRIVE_LINK"
  introduction:
    title: Introduction
    content: |
      This section provides an introduction to your project. 
      [Add detailed information here.]
  methodology:
    title: Methodology
    content: |
      Here, you'll describe the methods used in your project.
      [Add detailed information here.]
  workflow:
    title: Workflow & Discussion
    content: |
      This section details the workflow and offers a discussion of the results.
      [Add detailed information here.]

# Custom CSS for parallax effect (you can expand this later)
sass:
  style: |
    body {
      margin: 0;
      font-family: sans-serif;
    }
    .parallax-section {
      position: relative;
      height: 100vh;
      overflow: hidden;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      text-align: center;
      color: white;
      background-size: cover;
      background-position: center;
      background-attachment: fixed; /* Parallax effect */
    }
    .parallax-section:nth-child(1) {
      background-image: url('assets/landing_bg.jpg'); /* Replace with your image */
    }
    .parallax-section:nth-child(2) {
      background-image: url('assets/intro_bg.jpg'); /* Replace with your image */
      color: black;
    }
    .parallax-section:nth-child(3) {
      background-image: url('assets/method_bg.jpg'); /* Replace with your image */
      color: black;
    }
    .parallax-section:nth-child(4) {
      background-image: url('assets/workflow_bg.jpg'); /* Replace with your image */
      color: black;
    }
    .section-content {
      position: relative;
      z-index: 1;
      padding: 20px;
      background-color: rgba(255, 255, 255, 0.7); /* Optional overlay */
      max-width: 800px;
    }
    .icon-link {
      display: inline-block;
      margin: 10px;
    }
    .icon-link img {
        width: 50px;
        height: 50px;
    }